name: ds_tutorial
dependencies:
 - python=3.6
 - numpy
 - pandas
 - matplotlib
 - scikit-learn
 - seaborn
 - jupyter
 - pandas-datareader
 - pillow
 - cython
 - cudnn
 - opencv
 - lxml
 - beautifulsoup4
 - pip:
    - tensorflow
    - keras
    - tqdm
    - xgboost
    - lightgbm
