name: ds_tutorial
channels:
 - conda-forge
dependencies:
 - python=3.6
 - numpy
 - pandas
 - matplotlib
 - scikit-learn
 - seaborn
 - jupyter
 - jupyter_contrib_nbextensions
 - pandas-datareader
 - keras
 - pillow
 - cython
 - tensorflow-gpu  # gce cloud tpu
 - oauth2client  # gce cloud tpu
 - google-api-python-client  # gce cloud tpu
